### ISSUE TITLE
Create visualizations of data trends for historical data

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#2]
Parent Story: [https://github.com/seng499-company2/algorithm2/issues/1](url)

Create visualizations of data trends for historical data (class size)(waitlist size)(# of people in year)

**Comment by JonahKoebernick** [comment]
Visualize trends by term, e.i, CSC 111 F2018, F2019, F2020. Analyzing by course overall is going to change significantly depending on the term.
